// <auto-generated />
using System;
using Aritz.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aritz.Server.Migrations
{
    [DbContext(typeof(AritzDbContext))]
    partial class AritzDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Aritz.Server.Models.Cart", b =>
                {
                    b.Property<int>("CAR_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CAR_ID"));

                    b.Property<DateTime?>("CAR_CREATED_DATE")
                        .HasColumnType("datetime2");

                    b.Property<int>("CAR_USR_ID")
                        .HasColumnType("int")
                        .HasColumnName("CAR_USR_ID");

                    b.HasKey("CAR_ID");

                    b.HasIndex("CAR_USR_ID");

                    b.ToTable("Cart", (string)null);
                });

            modelBuilder.Entity("Aritz.Server.Models.CartItems", b =>
                {
                    b.Property<int>("CAI_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CAI_ID"));

                    b.Property<int>("CAI_CAR_ID")
                        .HasColumnType("int")
                        .HasColumnName("CAI_CAR_ID");

                    b.Property<int>("CAI_PRD_ID")
                        .HasColumnType("int")
                        .HasColumnName("CAI_PRD_ID");

                    b.Property<int>("CAI_QUANTITY")
                        .HasColumnType("int")
                        .HasColumnName("CAI_QUANTITY");

                    b.Property<decimal>("CAI_TOTAL_PRICE")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("CAI_TOTAL_PRICE");

                    b.HasKey("CAI_ID");

                    b.HasIndex("CAI_CAR_ID");

                    b.HasIndex("CAI_PRD_ID");

                    b.ToTable("CartItems", (string)null);
                });

            modelBuilder.Entity("Aritz.Server.Models.Category", b =>
                {
                    b.Property<int>("CAT_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CAT_ID"));

                    b.Property<DateTime?>("CAT_CREATED_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("CAT_DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CAT_NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CAT_NAME");

                    b.HasKey("CAT_ID");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("Aritz.Server.Models.OrderDetails", b =>
                {
                    b.Property<int>("ODD_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ODD_ID"));

                    b.Property<int>("ODD_ORD_ID")
                        .HasColumnType("int")
                        .HasColumnName("ODD_ORD_ID");

                    b.Property<int>("ODD_PRD_ID")
                        .HasColumnType("int")
                        .HasColumnName("ODD_PRD_ID");

                    b.Property<int>("ODD_QUANTITY")
                        .HasColumnType("int")
                        .HasColumnName("ODD_QUANTITY");

                    b.Property<decimal>("ODD_TOTAL_PRICE")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ODD_TOTAL_PRICE");

                    b.HasKey("ODD_ID");

                    b.HasIndex("ODD_ORD_ID");

                    b.HasIndex("ODD_PRD_ID");

                    b.ToTable("OrderDetails", (string)null);
                });

            modelBuilder.Entity("Aritz.Server.Models.Orders", b =>
                {
                    b.Property<int>("ORD_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ORD_ID"));

                    b.Property<DateTime>("ORD_ORDER_DATE")
                        .HasColumnType("datetime2")
                        .HasColumnName("ORD_ORDER_DATE");

                    b.Property<int>("ORD_PMT_ID")
                        .HasColumnType("int")
                        .HasColumnName("ORD_PMT_ID");

                    b.Property<string>("ORD_STATUS")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ORD_STATUS");

                    b.Property<decimal>("ORD_TOTAL_AMOUNT")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ORD_TOTAL_AMOUNT");

                    b.Property<int>("ORD_USR_ID")
                        .HasColumnType("int")
                        .HasColumnName("ORD_USR_ID");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ORD_ZIP_CODE");

                    b.HasKey("ORD_ID");

                    b.HasIndex("ORD_PMT_ID");

                    b.HasIndex("ORD_USR_ID");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("Aritz.Server.Models.Payment", b =>
                {
                    b.Property<int>("PAY_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PAY_ID"));

                    b.Property<decimal>("PAY_AMOUNT")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PAY_AMOUNT");

                    b.Property<int>("PAY_ORD_ID")
                        .HasColumnType("int")
                        .HasColumnName("PAY_ORD_ID");

                    b.Property<DateTime>("PAY_PAYMENT_DATE")
                        .HasColumnType("datetime2")
                        .HasColumnName("PAY_PAYMENT_DATE");

                    b.Property<string>("PAY_PAYMENT_REFERENCE")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PAY_PAYMENT_REFERENCE");

                    b.Property<string>("PAY_STATUS")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PAY_STATUS");

                    b.HasKey("PAY_ID");

                    b.HasIndex("PAY_ORD_ID");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("Aritz.Server.Models.PaymentMethod", b =>
                {
                    b.Property<int>("PMT_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PMT_ID"));

                    b.Property<string>("PMT_NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PMT_NAME");

                    b.HasKey("PMT_ID");

                    b.ToTable("PaymentMethod", (string)null);
                });

            modelBuilder.Entity("Aritz.Server.Models.Product", b =>
                {
                    b.Property<int>("PRD_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PRD_ID"));

                    b.Property<int>("PRD_CAT_ID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PRD_CREATED_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("PRD_DESCRIPTION")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("PRD_DESCRIPTION");

                    b.Property<string>("PRD_IMAGE")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PRD_IMAGE");

                    b.Property<bool?>("PRD_IS_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<string>("PRD_NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PRD_NAME");

                    b.Property<decimal>("PRD_PRICE")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PRD_PRICE");

                    b.Property<int>("PRD_QUANTITY")
                        .HasColumnType("int");

                    b.HasKey("PRD_ID");

                    b.HasIndex("PRD_CAT_ID");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("Aritz.Server.Models.ProductImage", b =>
                {
                    b.Property<int>("IMG_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IMG_ID"));

                    b.Property<int>("IMG_PRD_ID")
                        .HasColumnType("int");

                    b.Property<string>("IMG_URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IMG_ID");

                    b.HasIndex("IMG_PRD_ID");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("Aritz.Server.Models.Receipts", b =>
                {
                    b.Property<int>("RCP_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RCP_ID"));

                    b.Property<int>("RCP_ORD_ID")
                        .HasColumnType("int")
                        .HasColumnName("RCP_ORD_ID");

                    b.Property<string>("RCP_PATH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RCP_PATH");

                    b.Property<DateTime>("RCP_UPLOAD_DATE")
                        .HasColumnType("datetime2")
                        .HasColumnName("RCP_UPLOAD_DATE");

                    b.HasKey("RCP_ID");

                    b.HasIndex("RCP_ORD_ID")
                        .IsUnique();

                    b.ToTable("Receipts", (string)null);
                });

            modelBuilder.Entity("Aritz.Server.Models.ShippingZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxZipCode")
                        .HasColumnType("int");

                    b.Property<int>("MinZipCode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ShippingZones");
                });

            modelBuilder.Entity("Aritz.Server.Models.Users", b =>
                {
                    b.Property<int>("USR_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("USR_ID"));

                    b.Property<string>("USR_APARTMENT")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USR_APARTMENT");

                    b.Property<string>("USR_CITY")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USR_CITY");

                    b.Property<DateTime?>("USR_CREATED_DATE")
                        .HasColumnType("datetime2")
                        .HasColumnName("USR_CREATED_DATE");

                    b.Property<string>("USR_DOCUMENT_NUMBER")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USR_DOCUMENT_NUMBER");

                    b.Property<string>("USR_DOCUMENT_TYPE")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USR_DOCUMENT_TYPE");

                    b.Property<string>("USR_EMAIL")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("USR_EMAIL");

                    b.Property<string>("USR_FLOOR")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USR_FLOOR");

                    b.Property<bool?>("USR_IS_ADMIN")
                        .HasColumnType("bit")
                        .HasColumnName("USR_IS_ADMIN");

                    b.Property<bool>("USR_IS_VERIFIED")
                        .HasColumnType("bit");

                    b.Property<string>("USR_NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("USR_NAME");

                    b.Property<string>("USR_NEW_PASSWORD_HASH")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USR_NEW_PASSWORD_HASH");

                    b.Property<string>("USR_PASSWORD_HASH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USR_PASSWORD_HASH");

                    b.Property<string>("USR_PHONE_NUMBER")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("USR_PHONE_NUMBER");

                    b.Property<string>("USR_POSTAL_CODE")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USR_POSTAL_CODE");

                    b.Property<string>("USR_PROVINCE")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USR_PROVINCE");

                    b.Property<string>("USR_STREET")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USR_STREET");

                    b.Property<string>("USR_STREET_NUMBER")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USR_STREET_NUMBER");

                    b.Property<string>("USR_SURNAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("USR_SURNAME");

                    b.Property<string>("USR_VERIFICATION_CODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("USR_VERIFICATION_EXPIRATION")
                        .HasColumnType("datetime2");

                    b.HasKey("USR_ID");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Aritz.Server.Models.Cart", b =>
                {
                    b.HasOne("Aritz.Server.Models.Users", "Users")
                        .WithMany()
                        .HasForeignKey("CAR_USR_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Aritz.Server.Models.CartItems", b =>
                {
                    b.HasOne("Aritz.Server.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CAI_CAR_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aritz.Server.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("CAI_PRD_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Aritz.Server.Models.OrderDetails", b =>
                {
                    b.HasOne("Aritz.Server.Models.Orders", "Orders")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ODD_ORD_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aritz.Server.Models.Product", "Products")
                        .WithMany()
                        .HasForeignKey("ODD_PRD_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Orders");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Aritz.Server.Models.Orders", b =>
                {
                    b.HasOne("Aritz.Server.Models.PaymentMethod", "PaymentMethod")
                        .WithMany("Orders")
                        .HasForeignKey("ORD_PMT_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Aritz.Server.Models.Users", "Users")
                        .WithMany()
                        .HasForeignKey("ORD_USR_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PaymentMethod");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Aritz.Server.Models.Payment", b =>
                {
                    b.HasOne("Aritz.Server.Models.Orders", "Orders")
                        .WithMany()
                        .HasForeignKey("PAY_ORD_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Aritz.Server.Models.Product", b =>
                {
                    b.HasOne("Aritz.Server.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("PRD_CAT_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Aritz.Server.Models.ProductImage", b =>
                {
                    b.HasOne("Aritz.Server.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("IMG_PRD_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Aritz.Server.Models.Receipts", b =>
                {
                    b.HasOne("Aritz.Server.Models.Orders", "Orders")
                        .WithOne("Receipt")
                        .HasForeignKey("Aritz.Server.Models.Receipts", "RCP_ORD_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Aritz.Server.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Aritz.Server.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Aritz.Server.Models.Orders", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Receipt")
                        .IsRequired();
                });

            modelBuilder.Entity("Aritz.Server.Models.PaymentMethod", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Aritz.Server.Models.Product", b =>
                {
                    b.Navigation("ProductImages");
                });
#pragma warning restore 612, 618
        }
    }
}
